wd: /data/svbench-chr21/SMK-OUT
#
ref:
  hg19: /data/svbench-chr21/hg19.ref.fa
  hg38: /data/svbench-chr21/hg38.ref.fa
  chm13: /data/svbench-chr21/chm13.ref.fa
trf:
  hg19: /data/svbench-chr21/hg19.trf.bed
  hg38: /data/svbench-chr21/hg38.trf.bed
  chm13: /data/svbench-chr21/chm13.trf.bed
strat:
  easy:
    hg19: /data/svbench-chr21/giab-strats/easy/hg19.bed
    hg38: /data/svbench-chr21/giab-strats/easy/hg38.bed
    chm13: /data/svbench-chr21/giab-strats/easy/chm13.bed
  hard:
    hg19: /data/svbench-chr21/giab-strats/hard/hg19.bed
    hg38: /data/svbench-chr21/giab-strats/hard/hg38.bed
    chm13: /data/svbench-chr21/giab-strats/hard/chm13.bed
#
# TODO: allows for more samples
name: HG002
fq: /data/svbench-chr21/reads.fq.gz
haps:
  hprc:
    - /data/svbench-chr21/hap1.fa.gz
    - /data/svbench-chr21/hap2.fa.gz
  giab:
    - /data/svbench-chr21/hap1.fa.gz
    - /data/svbench-chr21/hap2.fa.gz
#
# XXX: make a truthsets:
giab11:
  vcf:
    hg19: /data/svbench-chr21/hg19.giab11.vcf.gz
    hg38: /data/svbench-chr21/hg38.giab11.vcf.gz
    chm13: /data/svbench-chr21/chm13.giab11.vcf.gz
  bed:
    hg19: /data/svbench-chr21/hg19.giab11.bed
    hg38: /data/svbench-chr21/hg38.giab11.bed
    chm13: /data/svbench-chr21/chm13.giab11.bed
giab06:
  vcf:
    hg19: /data/svbench-chr21/giab06.vcf.gz
  bed:
    hg19: /data/svbench-chr21/giab06.bed
#
asm-callers:
  - dipcall
  - svim-asm
  - hapdiff
#
callers:
  debreak:
    s:
      - 0
      - 2
      - 4
    q:
      - 0
      - 10
      - 20
  sawfish:
    s:
      - 0
    q:
      - 0
      - 10
      - 20
  sniffles:
    s:
      - 0
      - 2
      - 4
    q:
      - 0
      - 10
      - 20
  cutesv:
    s:
      - 2
      - 4
    q:
      - 0
      - 10
      - 20
  severus:
    s:
      - 2
      - 4
    q:
      - 0
      - 10
      - 20
  svisionpro:
    s:
      - 2
      - 4
    q:
      - 0
      - 10
      - 20
  SVDSS:
    s:
      - 2
      - 4
    q:
      - 0
